class Cart < ActiveRecord::Base
  #AD UN CARRELLO POSSO ASSOCIARE PIÙ RIGHE D'ORDINE
  #INOLTRE CON LA CHIAMATA DESTROY LE RIGHE DIPENDONO DAL CARRELLO, SE DISTRUGGO IL CARRELLO DISTRUGGO ANCHE LE RIGHE
  has_many :line_items, dependent: :destroy
end
